name: Need QA Approve

on:
    pull_request_review:
        types: [submitted, edited, dismissed]
env:
    PANDA_TEAM_DEV: '["Jin39"]'
    PANDA_TEAM_QA: '["LeoLeoLeoLei"]'
    PR_NUMBER: ${{ github.event.pull_request.number }}
    REPO_NAME: ${{ github.repository }}

jobs:
  check-If-QA-approved:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: Check_PR_Author_Result
          path: /tmp

      - name: Get GitHub Pull Request Reviews
        id: get-reviewers
        uses: LiamPerson/get-reviews-action@v1.1.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_REQUEST_ID: ${{ env.PR_NUMBER }}
          GITHUB_REPOSITORY: ${{ env.REPO_NAME }}

      - name: Check If QA approved
        id: check-If-QA-approved
        uses: actions/github-script@v7
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          script: |
            const fs = require('fs')
            const authorIsFromPandaTeam = fs.readFileSync('/tmp/Check_PR_Author_Result.txt').toString()
            console.log('authorIsFromPandaTeam', authorIsFromPandaTeam)
            const reviewsObj = fs.readFileSync('${{ steps.get-reviewers.outputs.reviews_file_path }}')
            const approvedReviews = JSON.parse(reviewsObj).filter(reviewer => reviewer.state === 'APPROVED')
            const pandaTeamQAReviewers = JSON.parse(process.env.PANDA_TEAM_QA)
            const foundQAApprovedList = approvedReviews.filter(pandaTeamQA => pandaTeamQAReviewers.includes(pandaTeamQA.user.login))
            if (foundQAApprovedList.length > 0) {
                console.log("The PR is approved by QA")
            } else {
                throw new Error ("The PR is not approved by QA")
            }
