name: Need QA Approve

on:
  pull_request:
      branches: [main]
      types: [opened, ready_for_review, reopened, edited, synchronize]
  pull_request_review:
      types: [submitted, edited, dismissed]
env:
  PANDA_TEAM_DEV: '["Jin39"]'
  PANDA_TEAM_QA: '["LeoLeoLeoLei", "Jin39"]'
  PR_NUMBER: ${{ github.event.pull_request.number }}
  REPO_NAME: ${{ github.repository }}
  REPO_OWNER: ${{ github.repository_owner }}
  PR_OWNER: ${{ github.event.pull_request.user.login }}

jobs:
  check-If-QA-approved:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get GitHub Pull Request Reviews
        id: get-reviewers
        uses: LiamPerson/get-reviews-action@v1.1.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_REQUEST_ID: ${{ env.PR_NUMBER }}
          GITHUB_REPOSITORY: ${{ env.REPO_NAME }}

      - name: Check PR author
        id: check-PR-author
        if: ${{ contains(fromJson(env.PANDA_TEAM_DEV), env.PR_OWNER ) }}
        run: |
          echo "is_from_panda=true" >> $GITHUB_OUTPUT
      - if: ${{ !contains(fromJson(env.PANDA_TEAM_DEV), env.PR_OWNER ) }}
        run: |
          echo "is_from_panda=false" >> $GITHUB_OUTPUT

      - name: Check If QA approved
        id: check-If-QA-approved
        uses: actions/github-script@v7
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          script: |
            if('${{ steps.check-PR-author.outputs.is_from_panda }}' === 'true') {
              const fs = require('fs')
              const reviewsObj = fs.readFileSync('${{ steps.get-reviewers.outputs.reviews_file_path }}')
              const approvedReviews = JSON.parse(reviewsObj).filter(reviewer => reviewer.state === 'APPROVED')
              console.log(approvedReviews);
              const pandaTeamQAReviewers = JSON.parse(process.env.PANDA_TEAM_QA)
              console.log(pandaTeamQAReviewers);
              const foundQAApprovedList = approvedReviews.filter(pandaTeamQA => pandaTeamQAReviewers.includes(pandaTeamQA.user.login))
              console.log(foundQAApprovedList);
              if (foundQAApprovedList.length > 0) {
                console.log("The PR is approved by QA")
              } else {
                throw new Error ("The PR is not approved by one of QA, please request QA approval before merging.")
              }
            } else {
              console.log("The PR author is not from the panda team, skip this job")
              exit 0
            }
