
name: Code Review

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: anc95/ChatGPT-CodeReview@main
        env:
          GITHUB_TOKEN: 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
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          MODEL:
          top_p: 1
          temperature: 1