name: linting CI

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]
  
jobs:
  yarn-install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: "yarn"
          cache-dependency-path: yarn.lock
          registry-url: "https://registry.npmjs.org"
  linting: 
    name: Changed Files Linting
    if: ${{ github.event_name == 'pull_request' }}
    continue-on-error: true
    runs-on: ubuntu-latest
    needs: yarn-install

    steps:
       - uses: actions/checkout@v3
       - name: Run lint-staged
          run: yarn lint-staged
