name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  yarn-install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: "yarn"
          cache-dependency-path: yarn.lock
          registry-url: "https://registry.npmjs.org"

      - uses: actions/cache@v3
        id: yarn-node_modules-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('yarn.lock') }}
          restore-keys: ${{ runner.os }}-node_modules-

      - name: install node_modules
        if: steps.yarn-node_modules-cache.outputs.cache-hit != 'true'
        run: yarn --cwd install --frozen-lockfile

  lint:
    name: admin portal lint staged
    runs-on: ubuntu-latest
    needs: yarn-install
    steps:
       - name: Checkout code
         uses: actions/checkout@v3
         with:
          fetch-depth: 0

       - name: Run lint-staged
         run: yarn lint-staged
