name: Need QA Approve

on:
  pull_request:
    branches: [main]
    types: [opened, ready_for_review, reopened, edited, synchronize]
  pull_request_review:
      types: [submitted]

env:
  #PANDA_TEAM_DEV: ("liuchuck, TurboLeiGlobalPay, LeoLeoLeoLei, WANG-Lisa, wbees, WangTao-CD, PuAlbert, LarryManMan, activebrook, yang-ting1, DragonLiParadise, jerryxie5214, HaotianF, zackdong1, fancyLiu55, kevinwang-active, Sred1992, DongminW, MarkPan726, BrainLei, MafeeWu, leon-liao1015, Jin39, Yukiwei1, LukeLiu-GP")
  #PANDA_TEAM_QA: ("leoleoleolei", "WANG-Lisa")
  PANDA_TEAM_DEV: '["LeoLeoLeoLei", "Jin39"]'
  PANDA_TEAM_QA: '["Jin39"]'
  PR_NUMBER: ${{ github.event.pull_request.number }}
  REPO_NAME: ${{ github.repository }}
  REPO_OWNER: ${{ github.repository_owner }}
  PR_OWNER: ${{ github.event.pull_request.user.login }}



jobs:
  check-If-QA-approved:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Get GitHub Pull Request Reviews
        id: get-reviewers
        uses: LiamPerson/get-reviews-action@v1.1.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_REQUEST_ID: ${{ env.PR_NUMBER }}
          GITHUB_REPOSITORY: ${{ env.REPO_NAME }}

      - name: Check PR author
        id: check-PR-author
        if: ${{ contains(fromJson(env.PANDA_TEAM_DEV), env.PR_OWNER ) }}
        run: |
          echo "The PR author is from the panda team"
          echo "is_from_panda=true" >> $GITHUB_OUTPUT
      - if: ${{ !contains(fromJson(env.PANDA_TEAM_DEV), env.PR_OWNER ) }}
        run: |
          echo "The PR author is not from the panda team"
          echo "is_from_panda=false" >> $GITHUB_OUTPUT

      - name: Skip job if the PR is not from Panda Team
        if: ${{ steps.check-PR-author.outputs.is_from_panda == 'false' }}
        run: |
          echo "The PR author is not in from the panda team. Skipping the job."
          exit 0

      - name: Check If QA approved
        id: check-If-QA-approved
        if: ${{ steps.check-PR-author.outputs.is_from_panda == 'true' }}
        uses: actions/github-script@v7
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          script: |
            const reviews = require('./reviewer.json')
            console.log('reviews', reviews)
            const pandaTeamQa = JSON.parse(process.env.PANDA_TEAM_QA)
            console.log('pandaTeamQa', pandaTeamQa)
              
