name: Check the PR author is not from the PandaTeam

on:
  pull_request:
    branches: [main]
    types: [opened, ready_for_review, reopened, edited, synchronize]
  workflow_run: 
    workflows: [Need QA Approve]
    types: [in_progress]

env:
  #PANDA_TEAM_DEV: ("liuchuck, TurboLeiGlobalPay, LeoLeoLeoLei, WANG-Lisa, wbees, WangTao-CD, PuAlbert, LarryManMan, activebrook, yang-ting1, DragonLiParadise, jerryxie5214, HaotianF, zackdong1, fancyLiu55, kevinwang-active, Sred1992, DongminW, MarkPan726, BrainLei, MafeeWu, leon-liao1015, Jin39, Yukiwei1, LukeLiu-GP")
  #PANDA_TEAM_QA: ("leoleoleolei", "WANG-Lisa")
  PANDA_TEAM_DEV: '["Jin39"]'
  PANDA_TEAM_QA: '["LeoLeoLeoLei"]'
  PR_NUMBER: ${{ github.event.pull_request.number }}
  REPO_NAME: ${{ github.repository }}
  REPO_OWNER: ${{ github.repository_owner }}
  PR_OWNER: ${{ github.event.pull_request.user.login }}

jobs:
  check-If-QA-approved:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check PR author
        id: check-PR-author
        if: ${{ contains(fromJson(env.PANDA_TEAM_DEV), env.PR_OWNER ) }}
        run: |
          echo "The PR author is from the panda team"
          echo "is_from_panda=true" >> $GITHUB_OUTPUT
      - if: ${{ !contains(fromJson(env.PANDA_TEAM_DEV), env.PR_OWNER ) }}
        run: |
          echo "The PR author is not from the panda team, skip this job"
          echo "is_from_panda=false" >> $GITHUB_OUTPUT
      - run: | 
          echo 'result ${{ toJson(steps.check-PR-author.outputs) }}'
          echo ${{ steps.check-PR-author.outputs.is_from_panda }} > /tmp/Check_PR_Author_Result.txt
      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: Check_PR_Author_Result.txt
          path: /tmp/Check_PR_Author_Result.txt
          overwrite: true
